spring:
  application:
    name: quiz-question-service
  boot:
    admin:
      client:
        url: http://localhost:9090/admin
        username: admin
        password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8082
