server:
  port: 8081

spring:
  application:
    name: user-service

  boot:
    admin:
      client:
        url: http://localhost:9090  # Admin Server URL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints
  endpoint:
    health:
      show-details: always  # Show detailed health status

